services:
  - type: web
    name: task-management-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false 